import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import { SidebarProvider } from "./context/SidebarContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TG Dash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <div className="relative flex flex-1 flex-col overflow-y-auto overflow-x-hidden">
              <Header />
              <main>{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
